### ISSUE TITLE
Bq20z45

### ISSUE THREAD

**Issue by mossana** [laszlodaniel/SmartBatteryHack#14]
Hello
         I have battery asus k53 . Battery have bq20z45
I connected to arduino mega 2560 but not found smbus (smart Battery hack) software
![Uploading 16097394138023633148397443180242.jpg…]()
 Can you help me.
Are bq20z45 have a different connection ?

**Comment by laszlodaniel** [comment]
Hi, check the wiring, try switching SDA/SCL pins around.

**Comment by mossana** [comment]
I check , in  Arduino code 
![16097515613901395131426917061731](https://user-images.githubusercontent.com/76933665/103519211-ce108600-4e7d-11eb-963d-162ca5f2cbcf.jpg)
Sda_pin 0
Scl_pin 1
I want change it to 
Sda_pin 20
Scl_pin 21
But give me error

**Comment by mossana** [comment]
My connection
![1609751749747788655363870105800](https://user-images.githubusercontent.com/76933665/103519461-3c554880-4e7e-11eb-9891-48f94b08623c.jpg)

**Comment by mossana** [comment]
Error when I changed pin 
![1609751861449178270877521237760](https://user-images.githubusercontent.com/76933665/103519615-7f172080-4e7e-11eb-9a42-ef103fb97dea.jpg)

**Comment by laszlodaniel** [comment]
Arduino Mega labels are not the same as the port/pin definitions.
PORTD 0 -> 20 (SDA)
PORTD 1 -> 21 (SCL)

Leave the original defines as they are by default.

I see the controller board is out of the battery unit. Is it powered up properly on all of its pins?
I tried the same with a bare board earlier, connected it to 12.6V, left the innermost cell pins disconnected and the Arduino didn't see the SMBus either. Then tried to tinker around until it released the magic smoke... Be careful.

**Comment by mossana** [comment]
I connected to battery 12.6
And I see it by i2c_scanner 
But when I use your software I can't connect (no  device give me )

**Comment by laszlodaniel** [comment]
Same here. Something's wrong with the address scanner in this particular sketch.
It's weird because it worked before.
I'll try to figure something out.

**Comment by mossana** [comment]
Ok thank you very much 💝

**Comment by laszlodaniel** [comment]
Check out the update. New Arduino sketch and GUI is uploaded. The communication is still choppy.
I'm still wondering what went wrong and why the code is acting up.

**Comment by mossana** [comment]
Thank you sir very much am glad for your help

**Comment by laszlodaniel** [comment]
You're welcome. Keep an eye out for further updates. The code needs more fixing.
I have other projects going so if you come up with solutions open a pull request.

**Comment by H-Masoumi** [comment]
Hi
I getting No SMBuss Device for BQ20Z75 too.
Output pins of battery are zero (P+ and P-). But the battery cells are full charge.
Also is this project dead? There is no new developments.
