### ISSUE TITLE
compile SmartBatteryHack

### ISSUE THREAD

**Issue by yo3gts** [laszlodaniel/SmartBatteryHack#21]
Hi, I need help to compile SmartBatteryHack.exe, I tried dotnet 3.5, 4 etc and nothing works.
Where can I find the ready executable?
Many thanks!
Dan

**Comment by laszlodaniel** [comment]
Target framework: .NET Framework 4.5 should work.

Compiled executable is in the "bin/Debug" folder:
https://github.com/laszlodaniel/SmartBatteryHack/raw/master/GUI/SmartBatteryHack/SmartBatteryHack/bin/Debug/SmartBatteryHack_GUI.zip
